name: app_movil
description: "Vibra Pay - App de pagos"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.6
  flutter_nfc_kit: ^3.6.2  # opcional
  qr_flutter: ^4.1.0          # Para generar QR
  qr_code_scanner: ^1.0.0     # Para escanear QR
  image_picker: ^1.0.0        # (opcional) para subir fotos
  share_plus: ^7.0.0          # (opcional) para compartir PDF
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true